# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/piotr/Development/C++/minecraft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/piotr/Development/C++/minecraft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/piotr/Development/C++/minecraft/CMakeFiles /Users/piotr/Development/C++/minecraft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/piotr/Development/C++/minecraft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minecraft

# Build rule for target.
minecraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minecraft
.PHONY : minecraft

# fast build rule for target.
minecraft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/build
.PHONY : minecraft/fast

src/lib/Game/DateTime.o: src/lib/Game/DateTime.cpp.o
.PHONY : src/lib/Game/DateTime.o

# target to build an object file
src/lib/Game/DateTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/DateTime.cpp.o
.PHONY : src/lib/Game/DateTime.cpp.o

src/lib/Game/DateTime.i: src/lib/Game/DateTime.cpp.i
.PHONY : src/lib/Game/DateTime.i

# target to preprocess a source file
src/lib/Game/DateTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/DateTime.cpp.i
.PHONY : src/lib/Game/DateTime.cpp.i

src/lib/Game/DateTime.s: src/lib/Game/DateTime.cpp.s
.PHONY : src/lib/Game/DateTime.s

# target to generate assembly for a file
src/lib/Game/DateTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/DateTime.cpp.s
.PHONY : src/lib/Game/DateTime.cpp.s

src/lib/Game/Game.o: src/lib/Game/Game.cpp.o
.PHONY : src/lib/Game/Game.o

# target to build an object file
src/lib/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/Game.cpp.o
.PHONY : src/lib/Game/Game.cpp.o

src/lib/Game/Game.i: src/lib/Game/Game.cpp.i
.PHONY : src/lib/Game/Game.i

# target to preprocess a source file
src/lib/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/Game.cpp.i
.PHONY : src/lib/Game/Game.cpp.i

src/lib/Game/Game.s: src/lib/Game/Game.cpp.s
.PHONY : src/lib/Game/Game.s

# target to generate assembly for a file
src/lib/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/Game.cpp.s
.PHONY : src/lib/Game/Game.cpp.s

src/lib/Game/GameObject.o: src/lib/Game/GameObject.cpp.o
.PHONY : src/lib/Game/GameObject.o

# target to build an object file
src/lib/Game/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/GameObject.cpp.o
.PHONY : src/lib/Game/GameObject.cpp.o

src/lib/Game/GameObject.i: src/lib/Game/GameObject.cpp.i
.PHONY : src/lib/Game/GameObject.i

# target to preprocess a source file
src/lib/Game/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/GameObject.cpp.i
.PHONY : src/lib/Game/GameObject.cpp.i

src/lib/Game/GameObject.s: src/lib/Game/GameObject.cpp.s
.PHONY : src/lib/Game/GameObject.s

# target to generate assembly for a file
src/lib/Game/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Game/GameObject.cpp.s
.PHONY : src/lib/Game/GameObject.cpp.s

src/lib/GameObjects/CrosshairObject.o: src/lib/GameObjects/CrosshairObject.cpp.o
.PHONY : src/lib/GameObjects/CrosshairObject.o

# target to build an object file
src/lib/GameObjects/CrosshairObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/CrosshairObject.cpp.o
.PHONY : src/lib/GameObjects/CrosshairObject.cpp.o

src/lib/GameObjects/CrosshairObject.i: src/lib/GameObjects/CrosshairObject.cpp.i
.PHONY : src/lib/GameObjects/CrosshairObject.i

# target to preprocess a source file
src/lib/GameObjects/CrosshairObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/CrosshairObject.cpp.i
.PHONY : src/lib/GameObjects/CrosshairObject.cpp.i

src/lib/GameObjects/CrosshairObject.s: src/lib/GameObjects/CrosshairObject.cpp.s
.PHONY : src/lib/GameObjects/CrosshairObject.s

# target to generate assembly for a file
src/lib/GameObjects/CrosshairObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/CrosshairObject.cpp.s
.PHONY : src/lib/GameObjects/CrosshairObject.cpp.s

src/lib/GameObjects/SunAndMoon.o: src/lib/GameObjects/SunAndMoon.cpp.o
.PHONY : src/lib/GameObjects/SunAndMoon.o

# target to build an object file
src/lib/GameObjects/SunAndMoon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/SunAndMoon.cpp.o
.PHONY : src/lib/GameObjects/SunAndMoon.cpp.o

src/lib/GameObjects/SunAndMoon.i: src/lib/GameObjects/SunAndMoon.cpp.i
.PHONY : src/lib/GameObjects/SunAndMoon.i

# target to preprocess a source file
src/lib/GameObjects/SunAndMoon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/SunAndMoon.cpp.i
.PHONY : src/lib/GameObjects/SunAndMoon.cpp.i

src/lib/GameObjects/SunAndMoon.s: src/lib/GameObjects/SunAndMoon.cpp.s
.PHONY : src/lib/GameObjects/SunAndMoon.s

# target to generate assembly for a file
src/lib/GameObjects/SunAndMoon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/SunAndMoon.cpp.s
.PHONY : src/lib/GameObjects/SunAndMoon.cpp.s

src/lib/GameObjects/WorldObject.o: src/lib/GameObjects/WorldObject.cpp.o
.PHONY : src/lib/GameObjects/WorldObject.o

# target to build an object file
src/lib/GameObjects/WorldObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/WorldObject.cpp.o
.PHONY : src/lib/GameObjects/WorldObject.cpp.o

src/lib/GameObjects/WorldObject.i: src/lib/GameObjects/WorldObject.cpp.i
.PHONY : src/lib/GameObjects/WorldObject.i

# target to preprocess a source file
src/lib/GameObjects/WorldObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/WorldObject.cpp.i
.PHONY : src/lib/GameObjects/WorldObject.cpp.i

src/lib/GameObjects/WorldObject.s: src/lib/GameObjects/WorldObject.cpp.s
.PHONY : src/lib/GameObjects/WorldObject.s

# target to generate assembly for a file
src/lib/GameObjects/WorldObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/GameObjects/WorldObject.cpp.s
.PHONY : src/lib/GameObjects/WorldObject.cpp.s

src/lib/Meshes/ChunkBuilder.o: src/lib/Meshes/ChunkBuilder.cpp.o
.PHONY : src/lib/Meshes/ChunkBuilder.o

# target to build an object file
src/lib/Meshes/ChunkBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/ChunkBuilder.cpp.o
.PHONY : src/lib/Meshes/ChunkBuilder.cpp.o

src/lib/Meshes/ChunkBuilder.i: src/lib/Meshes/ChunkBuilder.cpp.i
.PHONY : src/lib/Meshes/ChunkBuilder.i

# target to preprocess a source file
src/lib/Meshes/ChunkBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/ChunkBuilder.cpp.i
.PHONY : src/lib/Meshes/ChunkBuilder.cpp.i

src/lib/Meshes/ChunkBuilder.s: src/lib/Meshes/ChunkBuilder.cpp.s
.PHONY : src/lib/Meshes/ChunkBuilder.s

# target to generate assembly for a file
src/lib/Meshes/ChunkBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/ChunkBuilder.cpp.s
.PHONY : src/lib/Meshes/ChunkBuilder.cpp.s

src/lib/Meshes/ChunkMesh.o: src/lib/Meshes/ChunkMesh.cpp.o
.PHONY : src/lib/Meshes/ChunkMesh.o

# target to build an object file
src/lib/Meshes/ChunkMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/ChunkMesh.cpp.o
.PHONY : src/lib/Meshes/ChunkMesh.cpp.o

src/lib/Meshes/ChunkMesh.i: src/lib/Meshes/ChunkMesh.cpp.i
.PHONY : src/lib/Meshes/ChunkMesh.i

# target to preprocess a source file
src/lib/Meshes/ChunkMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/ChunkMesh.cpp.i
.PHONY : src/lib/Meshes/ChunkMesh.cpp.i

src/lib/Meshes/ChunkMesh.s: src/lib/Meshes/ChunkMesh.cpp.s
.PHONY : src/lib/Meshes/ChunkMesh.s

# target to generate assembly for a file
src/lib/Meshes/ChunkMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/ChunkMesh.cpp.s
.PHONY : src/lib/Meshes/ChunkMesh.cpp.s

src/lib/Meshes/CrosshairMesh.o: src/lib/Meshes/CrosshairMesh.cpp.o
.PHONY : src/lib/Meshes/CrosshairMesh.o

# target to build an object file
src/lib/Meshes/CrosshairMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/CrosshairMesh.cpp.o
.PHONY : src/lib/Meshes/CrosshairMesh.cpp.o

src/lib/Meshes/CrosshairMesh.i: src/lib/Meshes/CrosshairMesh.cpp.i
.PHONY : src/lib/Meshes/CrosshairMesh.i

# target to preprocess a source file
src/lib/Meshes/CrosshairMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/CrosshairMesh.cpp.i
.PHONY : src/lib/Meshes/CrosshairMesh.cpp.i

src/lib/Meshes/CrosshairMesh.s: src/lib/Meshes/CrosshairMesh.cpp.s
.PHONY : src/lib/Meshes/CrosshairMesh.s

# target to generate assembly for a file
src/lib/Meshes/CrosshairMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/CrosshairMesh.cpp.s
.PHONY : src/lib/Meshes/CrosshairMesh.cpp.s

src/lib/Meshes/Mesh.o: src/lib/Meshes/Mesh.cpp.o
.PHONY : src/lib/Meshes/Mesh.o

# target to build an object file
src/lib/Meshes/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/Mesh.cpp.o
.PHONY : src/lib/Meshes/Mesh.cpp.o

src/lib/Meshes/Mesh.i: src/lib/Meshes/Mesh.cpp.i
.PHONY : src/lib/Meshes/Mesh.i

# target to preprocess a source file
src/lib/Meshes/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/Mesh.cpp.i
.PHONY : src/lib/Meshes/Mesh.cpp.i

src/lib/Meshes/Mesh.s: src/lib/Meshes/Mesh.cpp.s
.PHONY : src/lib/Meshes/Mesh.s

# target to generate assembly for a file
src/lib/Meshes/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Meshes/Mesh.cpp.s
.PHONY : src/lib/Meshes/Mesh.cpp.s

src/lib/Player/Camera.o: src/lib/Player/Camera.cpp.o
.PHONY : src/lib/Player/Camera.o

# target to build an object file
src/lib/Player/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Player/Camera.cpp.o
.PHONY : src/lib/Player/Camera.cpp.o

src/lib/Player/Camera.i: src/lib/Player/Camera.cpp.i
.PHONY : src/lib/Player/Camera.i

# target to preprocess a source file
src/lib/Player/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Player/Camera.cpp.i
.PHONY : src/lib/Player/Camera.cpp.i

src/lib/Player/Camera.s: src/lib/Player/Camera.cpp.s
.PHONY : src/lib/Player/Camera.s

# target to generate assembly for a file
src/lib/Player/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Player/Camera.cpp.s
.PHONY : src/lib/Player/Camera.cpp.s

src/lib/Player/Player.o: src/lib/Player/Player.cpp.o
.PHONY : src/lib/Player/Player.o

# target to build an object file
src/lib/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Player/Player.cpp.o
.PHONY : src/lib/Player/Player.cpp.o

src/lib/Player/Player.i: src/lib/Player/Player.cpp.i
.PHONY : src/lib/Player/Player.i

# target to preprocess a source file
src/lib/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Player/Player.cpp.i
.PHONY : src/lib/Player/Player.cpp.i

src/lib/Player/Player.s: src/lib/Player/Player.cpp.s
.PHONY : src/lib/Player/Player.s

# target to generate assembly for a file
src/lib/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Player/Player.cpp.s
.PHONY : src/lib/Player/Player.cpp.s

src/lib/Renderer/Material.o: src/lib/Renderer/Material.cpp.o
.PHONY : src/lib/Renderer/Material.o

# target to build an object file
src/lib/Renderer/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Material.cpp.o
.PHONY : src/lib/Renderer/Material.cpp.o

src/lib/Renderer/Material.i: src/lib/Renderer/Material.cpp.i
.PHONY : src/lib/Renderer/Material.i

# target to preprocess a source file
src/lib/Renderer/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Material.cpp.i
.PHONY : src/lib/Renderer/Material.cpp.i

src/lib/Renderer/Material.s: src/lib/Renderer/Material.cpp.s
.PHONY : src/lib/Renderer/Material.s

# target to generate assembly for a file
src/lib/Renderer/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Material.cpp.s
.PHONY : src/lib/Renderer/Material.cpp.s

src/lib/Renderer/Renderer.o: src/lib/Renderer/Renderer.cpp.o
.PHONY : src/lib/Renderer/Renderer.o

# target to build an object file
src/lib/Renderer/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Renderer.cpp.o
.PHONY : src/lib/Renderer/Renderer.cpp.o

src/lib/Renderer/Renderer.i: src/lib/Renderer/Renderer.cpp.i
.PHONY : src/lib/Renderer/Renderer.i

# target to preprocess a source file
src/lib/Renderer/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Renderer.cpp.i
.PHONY : src/lib/Renderer/Renderer.cpp.i

src/lib/Renderer/Renderer.s: src/lib/Renderer/Renderer.cpp.s
.PHONY : src/lib/Renderer/Renderer.s

# target to generate assembly for a file
src/lib/Renderer/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Renderer.cpp.s
.PHONY : src/lib/Renderer/Renderer.cpp.s

src/lib/Renderer/Shader.o: src/lib/Renderer/Shader.cpp.o
.PHONY : src/lib/Renderer/Shader.o

# target to build an object file
src/lib/Renderer/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Shader.cpp.o
.PHONY : src/lib/Renderer/Shader.cpp.o

src/lib/Renderer/Shader.i: src/lib/Renderer/Shader.cpp.i
.PHONY : src/lib/Renderer/Shader.i

# target to preprocess a source file
src/lib/Renderer/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Shader.cpp.i
.PHONY : src/lib/Renderer/Shader.cpp.i

src/lib/Renderer/Shader.s: src/lib/Renderer/Shader.cpp.s
.PHONY : src/lib/Renderer/Shader.s

# target to generate assembly for a file
src/lib/Renderer/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Shader.cpp.s
.PHONY : src/lib/Renderer/Shader.cpp.s

src/lib/Renderer/Texture.o: src/lib/Renderer/Texture.cpp.o
.PHONY : src/lib/Renderer/Texture.o

# target to build an object file
src/lib/Renderer/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Texture.cpp.o
.PHONY : src/lib/Renderer/Texture.cpp.o

src/lib/Renderer/Texture.i: src/lib/Renderer/Texture.cpp.i
.PHONY : src/lib/Renderer/Texture.i

# target to preprocess a source file
src/lib/Renderer/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Texture.cpp.i
.PHONY : src/lib/Renderer/Texture.cpp.i

src/lib/Renderer/Texture.s: src/lib/Renderer/Texture.cpp.s
.PHONY : src/lib/Renderer/Texture.s

# target to generate assembly for a file
src/lib/Renderer/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Renderer/Texture.cpp.s
.PHONY : src/lib/Renderer/Texture.cpp.s

src/lib/Utils/AssetsManager.o: src/lib/Utils/AssetsManager.cpp.o
.PHONY : src/lib/Utils/AssetsManager.o

# target to build an object file
src/lib/Utils/AssetsManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Utils/AssetsManager.cpp.o
.PHONY : src/lib/Utils/AssetsManager.cpp.o

src/lib/Utils/AssetsManager.i: src/lib/Utils/AssetsManager.cpp.i
.PHONY : src/lib/Utils/AssetsManager.i

# target to preprocess a source file
src/lib/Utils/AssetsManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Utils/AssetsManager.cpp.i
.PHONY : src/lib/Utils/AssetsManager.cpp.i

src/lib/Utils/AssetsManager.s: src/lib/Utils/AssetsManager.cpp.s
.PHONY : src/lib/Utils/AssetsManager.s

# target to generate assembly for a file
src/lib/Utils/AssetsManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Utils/AssetsManager.cpp.s
.PHONY : src/lib/Utils/AssetsManager.cpp.s

src/lib/Window/Window.o: src/lib/Window/Window.cpp.o
.PHONY : src/lib/Window/Window.o

# target to build an object file
src/lib/Window/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Window/Window.cpp.o
.PHONY : src/lib/Window/Window.cpp.o

src/lib/Window/Window.i: src/lib/Window/Window.cpp.i
.PHONY : src/lib/Window/Window.i

# target to preprocess a source file
src/lib/Window/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Window/Window.cpp.i
.PHONY : src/lib/Window/Window.cpp.i

src/lib/Window/Window.s: src/lib/Window/Window.cpp.s
.PHONY : src/lib/Window/Window.s

# target to generate assembly for a file
src/lib/Window/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/Window/Window.cpp.s
.PHONY : src/lib/Window/Window.cpp.s

src/lib/World/Chunk.o: src/lib/World/Chunk.cpp.o
.PHONY : src/lib/World/Chunk.o

# target to build an object file
src/lib/World/Chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/World/Chunk.cpp.o
.PHONY : src/lib/World/Chunk.cpp.o

src/lib/World/Chunk.i: src/lib/World/Chunk.cpp.i
.PHONY : src/lib/World/Chunk.i

# target to preprocess a source file
src/lib/World/Chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/World/Chunk.cpp.i
.PHONY : src/lib/World/Chunk.cpp.i

src/lib/World/Chunk.s: src/lib/World/Chunk.cpp.s
.PHONY : src/lib/World/Chunk.s

# target to generate assembly for a file
src/lib/World/Chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/World/Chunk.cpp.s
.PHONY : src/lib/World/Chunk.cpp.s

src/lib/World/World.o: src/lib/World/World.cpp.o
.PHONY : src/lib/World/World.o

# target to build an object file
src/lib/World/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/World/World.cpp.o
.PHONY : src/lib/World/World.cpp.o

src/lib/World/World.i: src/lib/World/World.cpp.i
.PHONY : src/lib/World/World.i

# target to preprocess a source file
src/lib/World/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/World/World.cpp.i
.PHONY : src/lib/World/World.cpp.i

src/lib/World/World.s: src/lib/World/World.cpp.s
.PHONY : src/lib/World/World.s

# target to generate assembly for a file
src/lib/World/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/lib/World/World.cpp.s
.PHONY : src/lib/World/World.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

vendor/glad/glad.o: vendor/glad/glad.c.o
.PHONY : vendor/glad/glad.o

# target to build an object file
vendor/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/vendor/glad/glad.c.o
.PHONY : vendor/glad/glad.c.o

vendor/glad/glad.i: vendor/glad/glad.c.i
.PHONY : vendor/glad/glad.i

# target to preprocess a source file
vendor/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/vendor/glad/glad.c.i
.PHONY : vendor/glad/glad.c.i

vendor/glad/glad.s: vendor/glad/glad.c.s
.PHONY : vendor/glad/glad.s

# target to generate assembly for a file
vendor/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minecraft.dir/build.make CMakeFiles/minecraft.dir/vendor/glad/glad.c.s
.PHONY : vendor/glad/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... minecraft"
	@echo "... src/lib/Game/DateTime.o"
	@echo "... src/lib/Game/DateTime.i"
	@echo "... src/lib/Game/DateTime.s"
	@echo "... src/lib/Game/Game.o"
	@echo "... src/lib/Game/Game.i"
	@echo "... src/lib/Game/Game.s"
	@echo "... src/lib/Game/GameObject.o"
	@echo "... src/lib/Game/GameObject.i"
	@echo "... src/lib/Game/GameObject.s"
	@echo "... src/lib/GameObjects/CrosshairObject.o"
	@echo "... src/lib/GameObjects/CrosshairObject.i"
	@echo "... src/lib/GameObjects/CrosshairObject.s"
	@echo "... src/lib/GameObjects/SunAndMoon.o"
	@echo "... src/lib/GameObjects/SunAndMoon.i"
	@echo "... src/lib/GameObjects/SunAndMoon.s"
	@echo "... src/lib/GameObjects/WorldObject.o"
	@echo "... src/lib/GameObjects/WorldObject.i"
	@echo "... src/lib/GameObjects/WorldObject.s"
	@echo "... src/lib/Meshes/ChunkBuilder.o"
	@echo "... src/lib/Meshes/ChunkBuilder.i"
	@echo "... src/lib/Meshes/ChunkBuilder.s"
	@echo "... src/lib/Meshes/ChunkMesh.o"
	@echo "... src/lib/Meshes/ChunkMesh.i"
	@echo "... src/lib/Meshes/ChunkMesh.s"
	@echo "... src/lib/Meshes/CrosshairMesh.o"
	@echo "... src/lib/Meshes/CrosshairMesh.i"
	@echo "... src/lib/Meshes/CrosshairMesh.s"
	@echo "... src/lib/Meshes/Mesh.o"
	@echo "... src/lib/Meshes/Mesh.i"
	@echo "... src/lib/Meshes/Mesh.s"
	@echo "... src/lib/Player/Camera.o"
	@echo "... src/lib/Player/Camera.i"
	@echo "... src/lib/Player/Camera.s"
	@echo "... src/lib/Player/Player.o"
	@echo "... src/lib/Player/Player.i"
	@echo "... src/lib/Player/Player.s"
	@echo "... src/lib/Renderer/Material.o"
	@echo "... src/lib/Renderer/Material.i"
	@echo "... src/lib/Renderer/Material.s"
	@echo "... src/lib/Renderer/Renderer.o"
	@echo "... src/lib/Renderer/Renderer.i"
	@echo "... src/lib/Renderer/Renderer.s"
	@echo "... src/lib/Renderer/Shader.o"
	@echo "... src/lib/Renderer/Shader.i"
	@echo "... src/lib/Renderer/Shader.s"
	@echo "... src/lib/Renderer/Texture.o"
	@echo "... src/lib/Renderer/Texture.i"
	@echo "... src/lib/Renderer/Texture.s"
	@echo "... src/lib/Utils/AssetsManager.o"
	@echo "... src/lib/Utils/AssetsManager.i"
	@echo "... src/lib/Utils/AssetsManager.s"
	@echo "... src/lib/Window/Window.o"
	@echo "... src/lib/Window/Window.i"
	@echo "... src/lib/Window/Window.s"
	@echo "... src/lib/World/Chunk.o"
	@echo "... src/lib/World/Chunk.i"
	@echo "... src/lib/World/Chunk.s"
	@echo "... src/lib/World/World.o"
	@echo "... src/lib/World/World.i"
	@echo "... src/lib/World/World.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... vendor/glad/glad.o"
	@echo "... vendor/glad/glad.i"
	@echo "... vendor/glad/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

